### ISSUE TITLE
v1 API is broken

### ISSUE THREAD

**Issue by ahwagner** [genome/dgi-db#143]
Updates to the data model in preparation for DGIdb v3 have disrupted the v1 API services. This should be fixed.

**Comment by susannasiebert** [comment]
Can you give me some more information on the v1 API services are currently disrupted?

**Comment by ahwagner** [comment]
Definitely.

http://127.0.0.1:3000/api/v1/interactions.json?genes=FLT1,MM1,FAKE returns `NoMethodError`.
