### ISSUE TITLE
By source table no longer displays correctly

### ISSUE THREAD

**Issue by malachig** [genome/dgi-db#15]
We now have enough sources that the 'By Source' tab does not render nicely.  This can be seen with the demo list of gene in the interaction search page.

http://dgidb.genome.wustl.edu/interaction_search_results

There a various ways we could fix this.  Quick and dirty could be to come up with shorter names for each source that show the complete name when we mouse over them.  Or the name could wrap instead of being only on a single line.  Or we could rework this table in some other way that still achieves the same effect of having only one row per unique drug-gene interaction with some concept of the independent support for that interaction being summarized.

**Comment by acoffman** [comment]
Yeah, you're definitely right - and presumably we'll only continue to add additional sources. I kind of like the visual aspect of the big table, just being able to see a lot of information at a glance, but perhaps that's not going to work long term.

I think we have the columns sorted by their trust and precedence ratings already. Perhaps we should just show the first 3 or 4 most "trustworthy" sources as columns and then the "count" column containing the total. Then maybe a mouseover or click of the count would display the full source list for that row?

Not sure that's any better, just a thought.

**Comment by ahwagner** [comment]
I like the idea of shorter names displayed with long name mouseovers. I'll look at this soon(ish).
