### ISSUE TITLE
bad_request question

### ISSUE THREAD

**Issue by ahwagner** [genome/dgi-db#26]
Is this a development artifact? It appears that we check for `:genes` in [this call](https://github.com/genome/dgi-db/blob/master/app/controllers/application_controller.rb#L36), instead of `:gene_categories`. I know that down the line we check `:gene_names` (generated from `:genes`) in `validate_interaction_request`. Should I patch this, or am I misunderstanding what's going on here?

**Comment by acoffman** [comment]
I'm not sure that I'm following the question - it looks like that method is called in 
````ruby
InteractionClaimsController#interaction_search_results
InteractionClaimsController#interactions_for_related_genes
ServicesV1Controller#related_genes
ServicesV1Controller#interactions
GenesController#categories_search_results
````

As far as I can tell, in each case `genes` is the required search parameter. `gene_categories` is generally used to filter the search results and comes in via the multiselect dropdown rather than user input (except in the services controller where it does come in as a param). Which endpoint are you looking at?

**Comment by ahwagner** [comment]
This is confusing to me too, as the error message reads `"Please enter at least one gene category to search!"`, so it seems natural that this should be checking `:gene_categories`, or that the error message should be changed. I got here through `InteractionClaimsController#interaction_search_results`. I should note that we do [appear to check](https://github.com/genome/dgi-db/blob/master/app/controllers/application_controller.rb#L49) that the gene list is not empty as well, which only adds to the confusion.

**Comment by acoffman** [comment]
Oh! I've missed the forest for the trees haha. Yeah, I think the error message is in fact erroneous. That method was likely extracted from validation we were doing on the gene categories search page and the error message wasn't made generic.

**Comment by ahwagner** [comment]
Great, thanks. I'll change the error message.
