### ISSUE TITLE
CIViC Updater Gene Count

### ISSUE THREAD

**Issue by ahwagner** [genome/dgi-db#32]
The CIViC updater should pull all genes. The updater should be fixed to query CIViC for the current gene count, rather than the hard-coded '80' it has now.

**Comment by nspies13** [comment]
Just fixed this, but may have screwed some things up when I pushed my merge... Can you check to see if the changes you made to my script are still there? Sorry!

**Comment by ahwagner** [comment]
Yeah, no problem. I’ll merge your updates into mine, and push the changes directly to master.

> On Aug 24, 2015, at 8:23 PM, Nick Spies <notifications@github.com> wrote:
> 
> Just fixed this, but may have screwed some things up when I pushed my merge... Can you check to see if the changes you made to my script are still there? Sorry!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/genome/dgi-db/issues/32#issuecomment-134436940>.
> 



____
This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.

**Comment by nspies13** [comment]
Great, thanks! Sorry again... Looks like that git tutorial can't come soon enough XD.
