### ISSUE TITLE
What order should interaction sources be?

### ISSUE THREAD

**Issue by bainscou** [genome/dgi-db#39]
View current order [here](https://github.com/genome/dgi-db/blob/master/app/sort_orders/interaction_result_sort_order.rb#L4-L27)

**Comment by obigriffith** [comment]
I propose the following order. First CIViC and DoCM, then expert-curated non-clinical-trial sources in same order as before, then expert-curated clinical-trial sources in same relative order as their non-clinical trial counterparts. Finally the non-expert-curated in their original relative order.

1 - 'CIViC'
2 - 'DoCM'
3 - 'MyCancerGenome'
4 - 'CancerCommons'
5 - 'ClearityFoundationBiomarkers'
6 - 'TALC'
7 - 'TEND'
8 - 'GuideToPharmacologyInteractions'

9 - 'MyCancerGenomeClinicalTrial'
10 - 'ClearityFoundationClinicalTrial'
11 - 'TdgClinicalTrial'

12 - 'PharmGKB'
13 - 'TTD'
14 - 'DrugBank'

**Comment by ahwagner** [comment]
I agree with CIViC and DoCM at the top of this list, since those interactions are expert-curated (only high-quality CIViC interactions are imported, right?) and based on clinical data. Why are the clinical trial sources in the second group, @obigriffith? Wouldn't non-clinical-trial resources include experimental results, and thus be of less interest from a precision medicine standpoint? Or am I thinking of this wrong?

**Comment by malachig** [comment]
I believe each of these "clinical trial" sources involved some kind of automated querying of the clinical trials database.  Perhaps that is why @obigriffith ranks them a bit lower.  However, some were also manually curated after the fact weren't they?  If so, I tend to agree with @ahwagner that their clinical nature should perhaps allow them to be ranked higher...

**Comment by obigriffith** [comment]
Yeah. I guess I just trust the quality of data from clinical trials a bit less. These really aren't created proper entries for genes, or drugs, so even with curation the interaction can be a bit uncertain. They also get "dated" quickly as trials come to an end.

**Comment by ahwagner** [comment]
After giving it more thought, I agree with the ordering proposed by @obigriffith. CIViC and DoCM serve as continually revised, high-quality versions of clinically actionable interactions, whereas our other such sources are stale (and in some cases, several years so). If we automatically update the `MyCancerGenomeClinicalTrial` or `ClearityFoundationClinicalTrial` sources, then we should revisit moving them higher on this list. Can I get a +1 to make this change in code?

**Comment by obigriffith** [comment]
Easy +1 from me since I suggested it. :-) Looks good.
