### ISSUE TITLE
Interaction search results by source page not working well with so many sources

### ISSUE THREAD

**Issue by obigriffith** [genome/dgi-db#42]
Now with so many sources, the "by source" page is spilling over itself in an unattractive way. The main issue is that the column width is determined by the length of the source name and there are so many sources with long names that they make a really wide table. Maybe we could abbreviate or truncate with mouse-over for the full name?

![dgidb - interaction search results](https://cloud.githubusercontent.com/assets/1638042/9559495/071219a2-4dba-11e5-86a0-52f52088ee0c.png)

**Comment by ahwagner** [comment]
This is a long-standing issue that is on the short list of upcoming fixes. See #15.
