### ISSUE TITLE
Drug-gene interactions from CIVIC for query list of drugs report gene ID instead of symbol

### ISSUE THREAD

**Issue by malachig** [genome/dgi-db#49]
On the live site.

I searched for ERLOTINIB, IBRUTINIB, and LAPATINIB.

For CIViC results and and various other sources as well, the "Gene" shown is the Entrez ID instead of the Entrez gene symbol.  Even if Entrez ID was available shouldn't these have been imported with the Gene Symbol as their gene record?

For example I get an 'ERLOTINIB' and '19' drug-gene interaction.  19 is EGFR.

I also see appear to be duplicate interactions from CIViC.  For example,
http://dgidb.genome.wustl.edu/interaction_claims/bd41a7e7-4ac6-45bd-9f0f-71e2daedfad5
http://dgidb.genome.wustl.edu/interaction_claims/9e2984b9-d532-476b-b1f2-f4c6b8bc5bdc

When I query from the gene direction and enter 'EGFR' I get a gene-drug interaction with 'ERLOTINIB'. So that looks nicer though I see all the same duplicate entries there as well of course.

![screen shot 2015-08-31 at 11 13 21 am](https://cloud.githubusercontent.com/assets/856728/9583497/4e755732-4fd1-11e5-8f32-8b3cdf9df621.png)

**Comment by malachig** [comment]
Looks like `TALC` and `GuideToPharmacologyInteractions` have a similar issue with Entrez Gene ID being displayed even though an official gene symbol is available.

**Comment by ahwagner** [comment]
Yeah. I noticed the same--the two solutions are to always use gene symbol as the import ID, or to have some sort of "primary name" concept (analogous to what we do with drugs). I prefer the latter. As for the duplicate entries, that escaped my notice. We definitely need to do something about that.

**Comment by malachig** [comment]
I believe in the past we chose to use Gene Symbol as the import ID in cases where we were reasonably confident that it was an official Entrez Gene Symbol and would map reasonably well to Entrez Gene Symbols in DGIdb.  In the case of CIViC we enforce use of official Entrez Gene names so this seems good.

I thought we also had somewhere the concept of using Entrez ID where available but still entering the Symbol as the official name during import...

**Comment by ahwagner** [comment]
Ah. We can definitely make that change for the CIViC importer, then. We will also need to update CIViC to accept gene symbol lookups in the URL. To illustrate what I mean:

https://civic.genome.wustl.edu/#/events/genes/42 will work fine.
https://civic.genome.wustl.edu/#/events/genes/RET hangs.

GTP is the same way (although we obviously have less control over this):

http://www.guidetopharmacology.org/GRAC/ObjectDisplayForward?objectId=1797 will work.
http://www.guidetopharmacology.org/GRAC/ObjectDisplayForward?objectId=EGFR will not.

This may be an issue with the way we do linking now, though. I like the idea of keeping the primary record IDs consistent.
