### ISSUE TITLE
Update the Druggable gene TSV archive download

### ISSUE THREAD

**Issue by malachig** [genome/dgi-db#91]
The `Druggable gene TSV archive` is a collection of the TSV files used by the importers.

This is made available on the Downloads page for people who would prefer not to use the API (though we strongly encourage the API route).

http://dgidb.genome.wustl.edu/downloads
http://dgidb.genome.wustl.edu/downloads/druggable_gene_tsvs.tar.gz

**Comment by malachig** [comment]
The Interactions.tsv also should be updated:
http://dgidb.genome.wustl.edu/downloads/interactions.tsv

**Comment by malachig** [comment]
And the Categories.tsv
http://dgidb.genome.wustl.edu/downloads/categories.tsv

**Comment by malachig** [comment]
Also, did the postgres data.sql file get updated since the last major update?

**Comment by acoffman** [comment]
@malachig I will double check to confirm - but it should have. I believe that the deploy process loads the sql dump from the same repo that the download comes from, so they should be in sync.

**Comment by malachig** [comment]
@acoffman, thanks for looking into this. If this is true, then that is fantastic. Once confirmed I would like to note this on the download page so that it is more clear which of the static downloads are likely to synced vs. those that get done periodically.

**Comment by ahwagner** [comment]
@acoffman is correct. When installing (updating) DGIdb, the db is loaded directly from the `data.sql` file in the `data/` directory. Our last update of the underlying data was two months ago, with commit 3483808 of the data sub-repo.

**Comment by malachig** [comment]
Okay I modified the text on the downloads page with: https://github.com/genome/dgi-db/commit/d55836fe879165be4ca88f44be2e64620f4f2670

Leaving this issue open though since we still need to update the Druggable gene TSV archive, Interactions.tsv, and Categories.tsv.
